# Generated by Django 2.2.28 on 2023-05-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=2200)),
                ('media', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
